### ISSUE TITLE
PHP 7.4 support. Unparenthesized ternary operators are depreceated

### ISSUE THREAD

**Issue by forsvunnet** [krokedil/collector-checkout-for-woocommerce#102]
Eg.:

> Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in collector-checkout-for-woocommerce\classes\class-collector-checkout-confirmation.php on line 253

**Comment by taneliheikkinen** [comment]
Now with PHP 8.0, this is a Fatal error...

**Comment by NiklasHogefjord** [comment]
Hi,

Sorry for the very long delay. This is now fixed in [Develop branch](https://github.com/krokedil/collector-checkout-for-woocommerce/tree/develop) and will be released in the next version of the plugin.
