### ISSUE TITLE
Add check for if Collector returns a 403 error on update cart request.

### ISSUE THREAD

**Issue by MichaelBengtsson** [krokedil/collector-checkout-for-woocommerce#52]
https://github.com/krokedil/collector-checkout-for-woocommerce/blob/master/classes/requests/class-collector-checkout-requests-update-cart.php#L46-L52

Currently we don't check the response for an error. This should be added to avoid issues.

**Comment by NiklasHogefjord** [comment]
Fixed in cd4ab69c45cda3d121814a752ac45c90e23e3334
