### ISSUE TITLE
PHP notices

### ISSUE THREAD

**Issue by rafal-sokolowski** [krokedil/collector-checkout-for-woocommerce#54]
On the checkout page
`Notice: Undefined index: order_comments in /wp-content/plugins/collector-checkout-for-woocommerce/templates/form-checkout.php on line 21`

/wp-admin/edit.php?post_type=shop_order
`Notice: id was called incorrectly. Order properties should not be accessed directly. Backtrace: WP_List_Table->display, WP_List_Table->display_rows_or_placeholder, WP_Posts_List_Table->display_rows, WP_Posts_List_Table->_display_rows, WP_Posts_List_Table->single_row, WP_List_Table->single_row_columns, WP_Posts_List_Table->column_default, do_action('manage_shop_order_posts_custom_column'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Admin_List_Table->render_columns, WC_Admin_List_Table_Orders->render_order_number_column, WC_Order->get_order_number, apply_filters('woocommerce_order_number'), WP_Hook->apply_filters, Collector_Checkout_Post_Checkout->collector_order_number, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong...`

WP 4.9.8
WooCommerce 3.5.1
PHP 7.2.9 (cli) (built: Aug 23 2018 02:08:27) ( NTS )

**Comment by NiklasHogefjord** [comment]
Hi,
This should be fixed in be85ed140919e101d6ade8fceca7ae38d1315c3e & a329fe76eb841416ae933756ec4c1539d5d77dad. The change can be tested by Downloading the Develop branch. This change will be published as a new version within the next couple of days.

**Comment by MichaelBengtsson** [comment]
Closed since this has a fix.
