### ISSUE TITLE
Fatal error: undefined function get_current_screen() in 1.5.0

### ISSUE THREAD

**Issue by rafal-sokolowski** [krokedil/collector-checkout-for-woocommerce#90]
After installing 1.5.0, I got this error:

`Fatal error: Uncaught Error: Call to undefined function get_current_screen() in /wp-content/plugins/collector-checkout-for-woocommerce/classes/class-collector-checkout-gateway.php:23`

1.4.3 worked fine.

WordPress 5.3.2
WooCommerce 3.9.2
Storefront 2.5.3

No other plugins activated.

**Comment by NiklasHogefjord** [comment]
Thanks for the report. I've fixed this and released a new version (v1.5.1).

Please feel free to reopen this issue if the new version doesn't solve your problem.
