### ISSUE TITLE
Fallback order when account already registered

### ISSUE THREAD

**Issue by rafal-sokolowski** [krokedil/collector-checkout-for-woocommerce#96]
These are my settings:

WooCommerce / Settings / Accounts & Privacy

<img width="796" alt="image" src="https://user-images.githubusercontent.com/10531472/79605124-a57a0d80-80ef-11ea-9014-0cdeb472356a.png">

The problem is that orders of customers who have their accounts already registered are made as a fallback.

> This order was made as a fallback due to an error in the checkout (Error message: An account is already registered with your email address. Please log in.). Please verify the order with Collector.

How those customers should know that they need to log in first, before the checkout?

I used an "Approved" person from here:
https://checkout-documentation.collector.se/#test-credentials

Tested on a fresh WooCommerce install.

WordPress 5.4
WooCommerce 4.0.1
Collector Checkout for WooCommerce 1.5.2
Storefront 2.5.5

No other plugins activated.

**Comment by NiklasHogefjord** [comment]
Hi, sorry for the very late reply. We are working on version 2.0 of this plugin. The new version will solve this issue. I'm closing this issue now, but feel free to re-open it again if the new version doesn't fix your issue.
